### ISSUE TITLE
Datcore files in filepicker cannot be downloaded by interactive services

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1268]
**Steps to reproduce**
First you need to have API keys and secrets for datcore.
1. Go to the datcore storage
2. Drag and drop a file in the workbench (you'll see a file picker with the file)
3. Connect the file to a jupyterlab-math service
4. Open the jupyterlab and check if the file appears in ~/work/inputs_1. The file doesn't appear. In the Logger there's an error saying "Failed retrieving inputs"

Connecting and reconnecting the file picker to the service or closing/reopening the study doesn't work

**Expected Behavior**
Datcore files can be added to a project and directly used in an interactive service

**Environment**
osparc.io, osparc-master

**Additional context**
In storage, there are these logs. So I guess the problem is with datcore or our datcore adapter in storage.
```
2024-02-16T08:30:44.302641839Z log_level=ERROR | log_timestamp=2024-02-16 08:30:44,301 | log_source=servicelib.aiohttp.monitoring:middleware_handler(227) | log_uid=None | log_msg=Unexpected server error "<class 'aiohttp.web_exceptions.HTTPNotImplemented'>" from access: 172.13.199.72 "GET /v0/locations/1/files/N:package:4fdd589b-d588-4d8a-916c-d5d1575ab7ac/metadata" done in 0.00 secs. Responding with status 501
Traceback (most recent call last):
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/rest_middlewares.py", line 76, in _middleware_handler
    return await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/rest_middlewares.py", line 166, in _middleware_handler
    resp = await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_storage/utils_handlers.py", line 29, in dsm_exception_handler
    return await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/long_running_tasks/_error_handlers.py", line 14, in base_long_running_error_handler
    return await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_storage/handlers_files.py", line 91, in get_file_metadata
    data = await dsm.get_file(
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_storage/datcore_dsm.py", line 61, in get_file
    raise NotImplementedError
NotImplementedError
```

I am also attaching the full error stack from the webserver
[webserver-datcore-error.txt](https://github.com/ITISFoundation/osparc-issues/files/14308553/webserver-datcore-error.txt)

And attached full logs from the dynamic sidecar. 
[dy-sidecar_get_matadata.txt](https://github.com/ITISFoundation/osparc-issues/files/14309219/dy-sidecar_get_matadata.txt)

If a computational service is used instead of an interactive one, it works as expected

**Comment by elisabettai** [comment]
@GitHK, do you remember adding something to nodeports that requesting metadata for the inputs?
I see this in the dy-sidecar logs (full logs are attached above)
```
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_ports_v2/port_utils.py", line 195, in pull_file_from_store
    downloaded_file = await filemanager.download_path_from_s3(

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_ports_common/filemanager.py", line 148, in download_path_from_s3
    file_meta_data: FileMetaDataGet = await _get_file_meta_data(

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_ports_common/filemanager.py", line 451, in _get_file_meta_data
    file_metadata: FileMetaDataGet = await storage_client.get_file_metadata(
```

**Comment by GitHK** [comment]
let's ask @sanderegg about d'attore and what should work or not.
We did change that part regarding metadata in the last 3 to 4 months

**Comment by sanderegg** [comment]
@GitHK : that change was probably done by you for some reason. now it needs to be fixed for datcore or people cannot pass datcore based data in dynamic services anymore as this part is not implemented.

**Comment by GitHK** [comment]
Ahh I get it now. Yes we'd have to add it in there.

**Comment by GitHK** [comment]
In my mind in order to fix the issue we should implement the `get_file` inside the `datcore_dsm` @sanderegg does this sound right to you?

**Comment by sanderegg** [comment]
@GitHK totally so
