### ISSUE TITLE
Metamodeling: list arguments in API

### ISSUE THREAD

**Issue by cbujard** [ITISFoundation/osparc-issues#948]
```
Traceback (most recent call last):
  File "/home/jovyan/work/workspace/driver.py", line 100, in <module>
    main()
  File "/home/jovyan/work/workspace/driver.py", line 97, in main
    runsim(g, sys.argv[2], sys.argv[3])
  File "/home/jovyan/work/workspace/driver.py", line 69, in runsim
    y = f(x)
  File "/home/jovyan/work/workspace/rsinc.py", line 24, in rsinc
    job: Job = solvers_api.create_job(
  File "/home/jovyan/.venv/lib/python3.9/site-packages/osparc/api/solvers_api.py", line 61, in create_job
    return self.create_job_with_http_info(
  File "/home/jovyan/.venv/lib/python3.9/site-packages/osparc/api/solvers_api.py", line 179, in create_job_with_http_info
    return self.api_client.call_api(
  File "/home/jovyan/.venv/lib/python3.9/site-packages/osparc/api_client.py", line 387, in call_api
    return self.__call_api(
  File "/home/jovyan/.venv/lib/python3.9/site-packages/osparc/api_client.py", line 195, in __call_api
    response_data = self.request(
  File "/home/jovyan/.venv/lib/python3.9/site-packages/osparc/api_client.py", line 463, in request
    return self.rest_client.POST(
  File "/home/jovyan/.venv/lib/python3.9/site-packages/osparc/rest.py", line 343, in POST
    return self.request(
  File "/home/jovyan/.venv/lib/python3.9/site-packages/osparc/rest.py", line 255, in request
    raise ApiException(http_resp=r)
osparc.exceptions.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Content-Length': '469', 'Content-Type': 'application/json', 'Date': 'Fri, 05 May 2023 14:26:28 GMT', 'Server': 'uvicorn', 'Vary': 'Accept-Encoding, Accept-Encoding'})
HTTP response body: {"errors":[{"loc":["body","values","x"],"msg":"value is not a valid dict","type":"type_error.dict"},{"loc":["body","values","x"],"msg":"value is not a valid float","type":"type_error.float"},{"loc":["body","values","x"],"msg":"value is not a valid integer","type":"type_error.integer"},{"loc":["body","values","x"],"msg":"value could not be parsed to a boolean","type":"type_error.bool"},{"loc":["body","values","x"],"msg":"str type expected","type":"type_error.str"}]}
```

```
Traceback (most recent call last):
  File "/home/jovyan/work/workspace/driver.py", line 100, in <module>
    main()
  File "/home/jovyan/work/workspace/driver.py", line 97, in main
    runsim(g, sys.argv[2], sys.argv[3])
  File "/home/jovyan/work/workspace/driver.py", line 69, in runsim
    y = f(x)
  File "/home/jovyan/work/workspace/rsinc.py", line 41, in rsinc
    outputs: JobOutputs = solvers_api.get_job_outputs(solver.id, solver.version, job.id)
  File "/home/jovyan/.venv/lib/python3.9/site-packages/osparc/api/solvers_api.py", line 563, in get_job_outputs
    return self.get_job_outputs_with_http_info(
  File "/home/jovyan/.venv/lib/python3.9/site-packages/osparc/api/solvers_api.py", line 684, in get_job_outputs_with_http_info
    return self.api_client.call_api(
  File "/home/jovyan/.venv/lib/python3.9/site-packages/osparc/api_client.py", line 387, in call_api
    return self.__call_api(
  File "/home/jovyan/.venv/lib/python3.9/site-packages/osparc/api_client.py", line 195, in __call_api
    response_data = self.request(
  File "/home/jovyan/.venv/lib/python3.9/site-packages/osparc/api_client.py", line 439, in request
    return self.rest_client.GET(
  File "/home/jovyan/.venv/lib/python3.9/site-packages/osparc/rest.py", line 267, in GET
    return self.request(
  File "/home/jovyan/.venv/lib/python3.9/site-packages/osparc/rest.py", line 255, in request
    raise ApiException(http_resp=r)
osparc.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Length': '278', 'Content-Type': 'application/json', 'Date': 'Fri, 05 May 2023 14:30:13 GMT', 'Server': 'uvicorn', 'Vary': 'Accept-Encoding, Accept-Encoding'})
HTTP response body: {"errors":["1 validation error for Nodeports\ninputs -> __root__ -> x -> value\n  Invalid value in port 'x': -1.2 is not of type 'array' (type=value_error.port_validation.schema_error; port_key=x; schema_error_path=deque([]); schema_error_message=-1.2 is not of type 'array')"]}


Error: cannot open results file "y.out" for evaluation 1
```

**Comment by cbujard** [comment]
Here is the link to the study; you now have read/write access @pcrespov 
https://osparc-master.speag.com/#/study/0c71f640-9332-11ed-9760-02420a7ac55e
